#pragma once

#define MOROBOX8_MAX_PATH 256
#ifndef MOROBOX8_SCREEN_WIDTH
#define MOROBOX8_SCREEN_WIDTH 180
#endif
#ifndef MOROBOX8_SCREEN_HEIGHT
#define MOROBOX8_SCREEN_HEIGHT 180
#endif
#define MOROBOX8_NETRAM_SIZE 0x100
#define MOROBOX8_PKTRAM_SIZE 0x100
#define MOROBOX8_CART_PADDING 0x28F8
#define MOROBOX8_PALETTE_SIZE 64
#define MOROBOX8_BACKGROUND_LAYER_SIZE 256
#define MOROBOX8_SPRITE_LAYER_SIZE 256
#define MOROBOX8_CART_MAGIC_CODE "MB8\0"
#define MOROBOX8_CART_MAGIC_CODE_SIZE 4
#define MOROBOX8_CHUNK_NAME_SIZE 16
#define MOROBOX8_FILENAME_SIZE 256
#define MOROBOX8_MAGICCODE_SIZE 4
#define MOROBOX8_CARTNAME_SIZE 16
#define MOROBOX8_64K_MAX_CHUNKS 0
#define MOROBOX8_256K_MAX_CHUNKS 12
#define MOROBOX8_MAX_CHUNKS 127
#define MOROBOX8_CART_MAX_SIZE (sizeof(struct morobox8_cart) + (MOROBOX8_MAX_CHUNKS * sizeof(struct morobox8_cart_code_chunk)))
#define MOROBOX8_INFO_SIZE 1024
#define MOROBOX8_CHUNK_INVALID 255
#define MOROBOX8_LUA_EXT ".lua"
#define MOROBOX8_LUA_EXT_SIZE sizeof(MOROBOX8_LUA_EXT)
#define MOROBOX8_JS_EXT ".js"
#define MOROBOX8_JS_EXT_SIZE sizeof(MOROBOX8_JS_EXT)
#define MOROBOX8_LUA_MAIN "main" MOROBOX8_LUA_EXT
#define MOROBOX8_LUA_MAIN_SIZE sizeof(MOROBOX8_LUA_MAIN)
#define MOROBOX8_JS_MAIN "main" MOROBOX8_JS_EXT
#define MOROBOX8_JS_MAIN_SIZE sizeof(MOROBOX8_JS_MAIN)
#define MOROBOX8_DEFAULT_FONT_NAME "font.png"
#define MOROBOX8_DEFAULT_FONT_NAME_SIZE sizeof(MOROBOX8_DEFAULT_FONT_NAME)
#define MOROBOX8_BIOS_NAME "bios/bios.mb8"
/* Number of sprites in a tileset. */
#define MOROBOX8_TILESET_WIDTH 16
#define MOROBOX8_TILESET_HEIGHT 16
#define MOROBOX8_TILESET_SIZE (MOROBOX8_TILESET_WIDTH * MOROBOX8_TILESET_HEIGHT)
#define MOROBOX8_SPRITE_WIDTH 8
#define MOROBOX8_SPRITE_HEIGHT 8
#define MOROBOX8_PIXELS_PER_SPRITE (MOROBOX8_SPRITE_WIDTH * MOROBOX8_SPRITE_HEIGHT)
#define MOROBOX8_COLORS_PER_SPRITE 4
#define MOROBOX8_COLOR_RGB565 1
#define MOROBOX8_COLOR_RGBA 2
#ifndef MOROBOX8_COLOR_FORMAT
#define MOROBOX8_COLOR_FORMAT MOROBOX8_COLOR_RGBA
#endif
#if MOROBOX8_COLOR_FORMAT == MOROBOX8_COLOR_RGB565
#define MOROBOX8_BYTES_PER_COLOR 2
#elif MOROBOX8_COLOR_FORMAT == MOROBOX8_COLOR_RGBA
#define MOROBOX8_BYTES_PER_COLOR 4
#else
#define MOROBOX8_BYTES_PER_COLOR 1
#endif
#define MOROBOX8_VRAM_SIZE (MOROBOX8_SCREEN_WIDTH * MOROBOX8_SCREEN_HEIGHT * MOROBOX8_BYTES_PER_COLOR)
