#pragma once

#ifndef MOROBOX8_SCREEN_WIDTH
#define MOROBOX8_SCREEN_WIDTH 180
#endif
#ifndef MOROBOX8_SCREEN_HEIGHT
#define MOROBOX8_SCREEN_HEIGHT 180
#endif
#define MOROBOX8_NETRAM_SIZE 0x100
#define MOROBOX8_PKTRAM_SIZE 0x100
#define MOROBOX8_PALETTE_SIZE 64
#define MOROBOX8_BACKGROUND_LAYER_SIZE 256
#define MOROBOX8_SPRITE_LAYER_SIZE 256
/* Number of sprites in a tileset. */
#define MOROBOX8_TILESET_WIDTH 16
#define MOROBOX8_TILESET_HEIGHT 16
#define MOROBOX8_TILESET_SIZE (MOROBOX8_TILESET_WIDTH * MOROBOX8_TILESET_HEIGHT)
#define MOROBOX8_SPRITE_WIDTH 8
#define MOROBOX8_SPRITE_HEIGHT 8
#define MOROBOX8_PIXELS_PER_SPRITE (MOROBOX8_SPRITE_WIDTH * MOROBOX8_SPRITE_HEIGHT)
#define MOROBOX8_COLORS_PER_SPRITE 4
#define MOROBOX8_COLOR_RGB565 1
#define MOROBOX8_COLOR_RGBA 2
#ifndef MOROBOX8_COLOR_FORMAT
#define MOROBOX8_COLOR_FORMAT MOROBOX8_COLOR_RGB565
#endif
#if MOROBOX8_COLOR_FORMAT == MOROBOX8_COLOR_RGB565
#define MOROBOX8_BYTES_PER_COLOR 2
#else
#define MOROBOX8_BYTES_PER_COLOR 1
#endif
#define MOROBOX8_VRAM_SIZE (MOROBOX8_SCREEN_WIDTH * MOROBOX8_SCREEN_HEIGHT * MOROBOX8_BYTES_PER_COLOR)
