#pragma once

#ifndef MORONET8_SCREEN_WIDTH
#define MORONET8_SCREEN_WIDTH 180
#endif
#ifndef MORONET8_SCREEN_HEIGHT
#define MORONET8_SCREEN_HEIGHT 180
#endif
#define MORONET8_NETRAM_SIZE 0x100
#define MORONET8_PKTRAM_SIZE 0x100
#define MORONET8_PALETTE_SIZE 64
#define MORONET8_BACKGROUND_LAYER_SIZE 256
#define MORONET8_SPRITE_LAYER_SIZE 256
/* Number of sprites in a tileset. */
#define MORONET8_TILESET_WIDTH 16
#define MORONET8_TILESET_HEIGHT 16
#define MORONET8_TILESET_SIZE (MORONET8_TILESET_WIDTH * MORONET8_TILESET_HEIGHT)
#define MORONET8_SPRITE_WIDTH 8
#define MORONET8_SPRITE_HEIGHT 8
#define MORONET8_PIXELS_PER_SPRITE (MORONET8_SPRITE_WIDTH * MORONET8_SPRITE_HEIGHT)
#define MORONET8_COLORS_PER_SPRITE 4
#define MORONET8_COLOR_RGB565 1
#ifndef MORONET8_COLOR_FORMAT
#define MORONET8_COLOR_FORMAT MORONET8_COLOR_RGB565
#endif
#if MORONET8_COLOR_FORMAT == MORONET8_COLOR_RGB565
#define MORONET8_BYTES_PER_COLOR 2
#else
#define MORONET8_BYTES_PER_COLOR 1
#endif
#define MORONET8_VRAM_SIZE (MORONET8_SCREEN_WIDTH * MORONET8_SCREEN_HEIGHT * MORONET8_BYTES_PER_COLOR)