name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  html:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          npm i
          npm run build
          mkdir -p build
          cd build
          emcmake cmake ..
          cmake --build .
